#!/bin/bash

#Mount TOS Org QEMU drive.

echo EMU Mnt ~/tos_disk.qcow2, /dev/nbd0p1 /mnt/tos_diskc, /dev/nbd0p2 /mnt/tos_diskd
sudo modprobe nbd max_part=16
sudo qemu-nbd -c /dev/nbd0 ~/tos_disk.qcow2
sudo partprobe /dev/nbd0
sudo mkdir -p /mnt/tos_diskd
sudo mkdir -p /mnt/tos_diskc
sudo mount /dev/nbd0p2 /mnt/tos_diskd
sudo mount /dev/nbd0p2 /mnt/tos_diskc

